### ISSUE TITLE
Bug: validate `"format": "uri"` field even if it is not required

### ISSUE THREAD

**Issue by woodpig07** [Wiredcraft/jekyllpro-cms#43]
Reported by @samcheah 
```
      "cta": {
        "type": "string",
        "title": "Actions",
        "format": "uri"
      },
```
For a non-required field defined as above, user cannot submit the file if leave the field empty as it got validation error `does not conform to the "uri" format`

**Comment by JuhaS** [comment]
@haishanh It seems the problem here was with the library that we use that doesn't support empty value for `type=URI` even if it is not marked as `required`. We should check if there is way to fix this easily (maybe send `undefined` instead of `""` if empty or similar) or if we should use another type for this.

**Comment by woodpig07** [comment]
not relevant anymore
